language: node_js
services:
        - docker

before_install:
        - docker build -t mynode -f Dockerfile .
        - docker create -ti --name dummy mynode bash
        - docker cp dummy:/build/index.html index.html
        - docker rm -f dummy

script: ls

deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
                branch: deploy



